name: Build and Test

on: workflow_call

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn run build

    #   - name: Run tests
    #     run: yarn test
