name: Create Release

on:
  workflow_call:
    inputs:
      new_version:
        required: true
        type: string

jobs:
  create_release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update RELEASE.md
        run: |
          echo "## Release ${{ inputs.new_version }}" > new_release.md
          echo "S3 Website URL: ${{ env.website_url }}" >> new_release.md
          echo "" >> new_release.md
          git log --pretty=format:"* %s" $(git describe --tags --abbrev=0 @^)..@ >> new_release.md
          echo "" >> new_release.md
          cat RELEASE.md >> new_release.md
          mv new_release.md RELEASE.md
          cat RELEASE.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add RELEASE.md
          git commit -m "Update RELEASE.md for version ${{ inputs.new_version }}"
          git pull origin $(echo "${GITHUB_REF#refs/heads/}") --rebase
          git push origin HEAD:$(echo "${GITHUB_REF#refs/heads/}")

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ inputs.new_version }}
          release_name: Release ${{ inputs.new_version }}
          body: |
            ## Changes
            $(cat RELEASE.md)
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Compress dist folder
        run: zip -r dist.zip dist/

      - name: Upload dist folder to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist.zip
          asset_name: dist.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}