name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - master

permissions:
  id-token: write
  contents: write

jobs:
  build_and_test:
    uses: ./.github/workflows/build-and-test.yml

  versioning:
    needs: build_and_test
    uses: ./.github/workflows/versioning.yml

  deploy_to_s3:
    needs: versioning
    uses: ./.github/workflows/deploy-to-s3.yml
    with:
      environment: ${{ github.ref == 'refs/heads/develop' && 'development' || 'production' }}
      new_version: ${{ needs.versioning.outputs.new_version }}
    secrets: inherit

  create_release:
    needs: [versioning, deploy_to_s3]
    uses: ./.github/workflows/create-release.yml
    with:
      new_version: ${{ needs.versioning.outputs.new_version }}
      s3_website_url: ${{ needs.deploy_to_s3.outputs.s3_website_url }}
    secrets: inherit
